version: '3.5'

services:
  bot:
    container_name: spikenbot
    build: .
    restart: on-failure
    env_file: .env
    depends_on:
      - db
    networks:
      - db
  db:
    container_name: spikendb-docker
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-spiken}
      - POSTGRES_PASSWORD=${DB_PW:-spiken}
      - POSTGRES_DB=${DB_NAME:-spiken}
    volumes:
      - /var/lib/postgresql/data/:/data/db
    ports:
      - 5432:5432
    networks:
      - db
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER:-spiken}']
      interval: 1m30s
      timeout: 30s
      retries: 5

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge
