version: '3.5'

services:
  db:
    container_name: spikendb
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-spiken}
      - POSTGRES_PASSWORD=${DB_PW:-spiken}      
      - POSTGRES_DB=${DB_NAME:-spiken}
    volumes:
      - /var/lib/postgresql/data/:/data/db
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local
